- name: Install low level drivers
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - xf86-video-intel
    - mesa
- name: Install Xorg related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - xorg-server
    - xorg-xinit
    - xorg-xbacklight
    - xclip
    - arandr
    - redshift
    - xdotool
    - bspwm
    - sxhkd
    - i3lock
    - unclutter
    - dunst
    - dmenu
    - rofi
    - xwallpaper
    - feh
    - sxiv
    - shotgun
    - slop
