- name: Install low level drivers
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.drivers }}"
- name: Install Xorg related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.xorg }}"

- name: Install fonts
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.fonts }}"
