---
- name: Create .config folder structure
  ansible.builtin.file:
    path: "/home/guru/.config/{{ item }}"
    state: directory
  loop: "{{ folders.package }}"

- name: Create data folder structure
  ansible.builtin.file:
    path: "/home/guru/.local/{{ item }}"
    state: directory
  loop: "{{ folders.data }}"

- name: Create home folder structure
  ansible.builtin.file:
    path: "/home/guru/{{ item }}"
    state: directory
  loop: "{{ folders.home }}"

- name: stow dotfiles
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop: "{{ stow }}"

- name: Download oh my zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh
    mode: 0700

- name: delete .ohmyzsh
  ansible.builtin.file:
    path: /home/guru/.oh-my-zsh
    state: absent

- name: Install oh my zsh
  ansible.builtin.script:
    cmd: /tmp/ohmyzsh.sh

- name: Install syntax highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/guru/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: delete .zshrc
  ansible.builtin.file:
    path: /home/guru/.zshrc
    state: absent

- name: Stow zsh
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dotfiles -t ~/ zsh"

- name: Install nvim Plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/guru/.local/share/nvim/site/autoload/plug.vim

- name: Stow nvim
  ansible.builtin.shell:
    cmd: "stow -d $HOME/dotfiles -t ~/ neovim"
