---
- name: Install core packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.core }}"

- name: Install FS related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.fs }}"

- name: Install core utils packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.utils }}"

- name: Install archiving and compression related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.archive }}"

- name: Install network and security related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.network }}"
