packages:
  drivers:
    - xf86-video-intel
    - mesa
  xorg:
    - xorg-server
    - xorg-xinit
    - xorg-xbacklight
    - xclip
    - arandr
    - redshift
    - xdotool
    - xdo
    - bspwm
    - sxhkd
    - i3lock
    - unclutter
    - dunst
    - dmenu
    - rofi
    - xwallpaper
    - feh
    - sxiv
    - shotgun
    - slop
  fonts:
    - noto-fonts-emoji
    - ttf-dejavu
    - ttf-droid
    - powerline-fonts
    - ttf-font-awesome
    - ttf-liberation
    - adobe-source-code-pro-fonts
