---
- name: Install container related packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.containers }}"

- name: Install virtualization packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.virtualization }}"
