- name: Document and image packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.documents }}"

- name: media packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.media }}"

- name: web and internet packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages.web }}"
