folders:
  package:
    - alacritty
    - aws
    - browser
    - bspwm
    - calcurse
    - containers
    - dunst
    - git
    - mpv
    - mpd
    - ncmpcpp
    - neomutt
    - neomutt/mutt
    - nvim
    - newsboat
    - polybar
    - rofi
    - surfraw
    - surfraw/elvi
    - sxhkd
    - tmux
    - tmux/conf/sessions
    - vifm
    - vifm/colors
    - vifm/scripts
    - youtube-dl
    - zathura
  data:
    - share/aspell
    - share/gpg
    - share/rofi
    - share/gnupg
    - share/applications
    - share/nvim/site/autoload
    - bin
  home:
    - .w3m
    - .w3m/cgi-bin
    - .ssh

stow:
  - alacritty
  - aws
  - browser
  - bspwm
  - calcurse
  - containers
  - data
  - dunst
  - git
  - gnupg
  - mimetypes
  - mpd
  - mpv
  - ncmpcpp
  - neomutt
  - neovim
  - newsboat
  - polybar
  - rofi
  - surfraw
  - scripts
  - sxhkd
  - tmux
  - vifm
  - w3m
  - wget
  - xorg
  - youtube-dl