---
- name: Install core packages using Pacman
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git
    - stow

- name: Clone dotfiles to home directory
  ansible.builtin.git:
    repo: https://github.com/Iduoad/dotfiles.git
    dest: "/home/{{ ansible_user }}/dotfiles"
